# Generated by Django 3.2 on 2023-07-01 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='mention',
            name='mentioned_by',
        ),
        migrations.AddField(
            model_name='mention',
            name='feedcomment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='feed.feedcomment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mention',
            name='mentioned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to=settings.AUTH_USER_MODEL),
        ),
    ]
