# Generated by Django 3.2 on 2023-07-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20230701_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mention',
        ),
    ]
