# Generated by Django 3.2 on 2023-07-01 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_delete_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, related_name='feeds_hashtag', to='feed.Hashtag'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
